boot.o: boot.S multiboot.h x86_desc.h types.h
handlers.o: handlers.S
x86_desc.o: x86_desc.S x86_desc.h types.h
file_sys_module.o: file_sys_module.c file_sys_module.h types.h \
  multiboot.h system_call.h paging.h x86_desc.h keyboard.h lib.h rtc.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c x86_desc.h types.h idt.h handler.h rtc.h keyboard.h lib.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  rtc.h keyboard.h paging.h file_sys_module.h system_call.h
keyboard.o: keyboard.c keyboard.h types.h lib.h i8259.h rtc.h
lib.o: lib.c lib.h types.h
paging.o: paging.c paging.h types.h x86_desc.h
rtc.o: rtc.c rtc.h types.h lib.h i8259.h keyboard.h
system_call.o: system_call.c system_call.h types.h paging.h x86_desc.h \
  keyboard.h lib.h rtc.h file_sys_module.h multiboot.h
